# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - deploy

test:
  stage: test
  script:
  - hugo --baseURL=https://danikarik.gitlab.io/akers/
  except:
  - master

pages:
  stage: deploy
  script:
  - hugo --baseURL=https://danikarik.gitlab.io/akers/
  artifacts:
    paths:
    - public
  only:
  - master
