baseURL: "http://localhost:1313/"
languageCode: "ru"
title: "АКЕРС-СТОМ"
copyright: "@SYSTEMD"
params:
  author: "Daniyar Baitursynov"
  description: "Медицинское оборудование и комплектующие"
  sections:
    hero:
      title: "АКЕРС-СТОМ"
      header: "Наши партнеры:"
      lead: "Медицинское оборудование и комплектующие."
    latest:
      title: "Новости и акции"
      header: "Новости и акции"
      lead: "Новости и акции"

