baseURL: "https://danikarik.gitlab.io/akers/"
languageCode: "ru"
title: "АКЕРС-СТОМ"
copyright: "ТОО \"АКЕРС-СТОМ\""
paginate: 6
params:
  author: "SYSTEMD"
  description: "Медицинское оборудование и комплектующие"
  sections:
    hero:
      title: "АКЕРС-СТОМ"
      header: "Наши партнеры:"
      lead: "Медицинское оборудование и комплектующие."
    blog:
      title: "Новости и акции"
      header: "Новости и акции"
      lead: "Новости и акции"
    contact:
      title: "Наши контакты"
      lead: "Свяжитесь с нами удобным для Вас способом"
      phone: "+7 (727) 279 84 35"
      mobile: "+7 (771) 507 77 49"
      fax: "+7 (727) 279 84 46"
      email: "info@akers.kz"
      address: "пр. СЕЙФУЛЛИНА 434, угол ул. ЖИБЕК ЖОЛЫ, оф. 105"


