---
label: product-item
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: description
  label: description
- type: file
  name: image
  label: image
pages:
- content/product/disinfection/автоклавы.md
