name: Build and Publish
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:

      - name: Set up Hugo
        run: |
          curl -LO https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.55.4_Linux-64bit.deb
          sudo dpkg -i hugo_0.55.4_Linux-64bit.deb

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: Build
        run: hugo -b $BASE_URL

      - name: Packing zip
        run: |
          cd public
          zip -r ${GITHUB_SHA} *
          mkdir -p build
          mv ${GITHUB_SHA}.zip build/${GITHUB_SHA}.zip

      - name: Publish source bundle
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        uses: actions/aws/cli@master
        with:
          args: s3 cp build/${GITHUB_SHA}.zip s3://${AWS_S3_BUCKET}/akers.kz/

